using System.Reflection;
using System.Text;
using System.Text.Json;
using BookAtrium.PluginContracts;
using BookAtrium.PluginContracts.Packaging;

namespace BookAtrium.PluginCli;

internal static class Program
{
    private const string ContractsPackageVersion = "2.1.1";

    public static async Task<int> Main(string[] args)
    {
        if (args.Length == 0 || args[0] is "-h" or "--help" or "help")
        {
            PrintHelp();
            return 0;
        }

        try
        {
            return args[0].ToLowerInvariant() switch
            {
                "new" => await CmdNew(args.Skip(1).ToArray()),
                "run" => CmdRun(args.Skip(1).ToArray()),
                "test" => CmdTest(args.Skip(1).ToArray()),
                "validate" => CmdValidate(args.Skip(1).ToArray()),
                "pack" => await CmdPack(args.Skip(1).ToArray()),
                "prepare-release" => await CmdPrepareRelease(args.Skip(1).ToArray()),
                _ => Fail($"Unknown command '{args[0]}'. Run bookatrium-plugin help.")
            };
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("error: " + ex.Message);
            return 1;
        }
    }

    private static void PrintHelp()
    {
        Console.WriteLine("""
            bookatrium-plugin — BookAtrium Plugin API 2.1 tooling (.NET 10)

            Commands:
              new <type> [--name ...] [--publisher ...] [--id ...] [--dir ...]
              run [--project <path>]
              test [--project <path>]
              validate [--project <path>]
              pack [--project <path>] [--out <dir>]
              prepare-release [--project <path>] [--out <dir>]

            Types: store, metadata-source, author-metadata-source,
                   metadata-reader, metadata-writer,
                   input-converter, output-converter, device

            Aliases: conversion-input, conversion-output

            Generated projects reference only BookAtrium.PluginContracts 2.1.1.
            Manifests and SHA-256 are generated by pack — do not hand-write plugin.json.
            """);
    }

    private static async Task<int> CmdNew(string[] args)
    {
        if (args.Length == 0)
            return Fail("Usage: bookatrium-plugin new <type> --name \"My Plugin\" --publisher \"Me\"");

        var type = args[0].ToLowerInvariant();
        var name = GetOpt(args, "--name") ?? "My Plugin";
        var publisher = GetOpt(args, "--publisher") ?? "Example Developer";
        var id = GetOpt(args, "--id") ?? $"com.example.{Slug(name)}";
        var dir = GetOpt(args, "--dir") ?? Path.Combine(Environment.CurrentDirectory, Slug(name));
        var contractsPath = GetOpt(args, "--contracts-path");

        var templateName = ResolveTemplateName(type);
        if (templateName is null)
            return Fail($"Unknown plugin type '{type}'.");

        var templateCs = FindTemplatePluginCs(templateName);
        if (templateCs is null)
            return Fail($"Template not found for type '{type}'.");

        Directory.CreateDirectory(dir);
        var className = SpanPascal(name) + "Plugin";
        var text = await File.ReadAllTextAsync(templateCs);
        text = ApplyPlaceholders(text, name, publisher, id, className);
        await File.WriteAllTextAsync(Path.Combine(dir, "Plugin.cs"), text);

        var projectName = Path.GetFileName(Path.GetFullPath(dir.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)));
        if (string.IsNullOrWhiteSpace(projectName))
            projectName = Slug(name);
        var csprojPath = Path.Combine(dir, projectName + ".csproj");
        await File.WriteAllTextAsync(csprojPath, GenerateCsproj(projectName, contractsPath, dir));

        Console.WriteLine($"Created {type} plugin at {dir}");
        Console.WriteLine("Next: edit Plugin.cs, then: bookatrium-plugin test && bookatrium-plugin pack");
        return 0;
    }

    private static int CmdRun(string[] args)
    {
        var project = ResolveProject(GetOpt(args, "--project"));
        Console.WriteLine("Plugin development mode:");
        Console.WriteLine($"  1. Build: dotnet build \"{project}\"");
        Console.WriteLine("  2. Launch BookAtrium with:");
        Console.WriteLine($"     BOOKATRIUM_PLUGIN_DEV_PATH=\"{Path.GetDirectoryName(project)}\"");
        Console.WriteLine("Dev load skips packaging; restart the app after rebuilds (hot reload when available).");
        return 0;
    }

    private static int CmdTest(string[] args)
    {
        var project = ResolveProject(GetOpt(args, "--project"));
        var dir = Path.GetDirectoryName(project)!;
        var testProj = Directory.GetFiles(dir, "*.Tests.csproj", SearchOption.AllDirectories).FirstOrDefault();
        if (testProj is null)
        {
            var parent = Path.GetDirectoryName(dir);
            if (!string.IsNullOrWhiteSpace(parent) && Directory.Exists(parent))
            {
                testProj = Directory.GetFiles(parent, Path.GetFileNameWithoutExtension(project) + ".Tests.csproj", SearchOption.AllDirectories)
                    .FirstOrDefault();
            }
        }

        if (testProj is null)
        {
            Console.WriteLine("No test project found. Running validate instead.");
            return CmdValidate(args);
        }

        return RunDotNet("test", testProj);
    }

    private static int CmdValidate(string[] args)
    {
        var project = ResolveProject(GetOpt(args, "--project"));
        var build = RunDotNet("build", project, "-c", "Release");
        if (build != 0)
            return build;

        var plugin = LoadPluginFromProject(project);
        var issues = new List<string>();
        if (string.IsNullOrWhiteSpace(plugin.Info.Id))
            issues.Add("BA1001: Plugin ID is missing");
        if (!PluginId.IsValid(plugin.Info.Id))
            issues.Add("BA1001: Plugin ID is invalid");
        if (!PluginSemanticVersion.TryParse(plugin.Info.Version, out _))
            issues.Add("BA1003: Plugin version must use semantic versioning");

        if (plugin.Info.Id.Contains("amazon", StringComparison.OrdinalIgnoreCase) && plugin.NetworkHosts.Count == 0)
            issues.Add("BA1002: Amazon store must declare allowed network hosts");

        var dll = PluginPackageBuilder.FindBuiltDll(project, "Release");
        var manifest = PluginManifestGenerator.FromPlugin(plugin, Path.GetFileName(dll), plugin.GetType().FullName!);
        var validation = PluginPackageManifestValidator.Validate(manifest);
        if (!validation.IsValid)
            issues.Add($"{validation.ErrorCode}: {validation.Message}");

        if (issues.Count > 0)
        {
            foreach (var issue in issues)
                Console.Error.WriteLine(issue);
            return 1;
        }

        Console.WriteLine("::notice::validate OK — " + plugin.Info.Id + " " + plugin.Info.Version + " (" + manifest.PluginType + ")");
        return 0;
    }

    private static Task<int> CmdPack(string[] args) => Task.FromResult(CmdPackCore(args));

    private static int CmdPackCore(string[] args)
    {
        var project = ResolveProject(GetOpt(args, "--project"));
        var outDir = GetOpt(args, "--out") ?? Path.Combine(Path.GetDirectoryName(project)!, "artifacts");
        Directory.CreateDirectory(outDir);

        if (RunDotNet("build", project, "-c", "Release") != 0)
            return 1;

        var plugin = LoadPluginFromProject(project);
        var dll = PluginPackageBuilder.FindBuiltDll(project, "Release");
        var entryAsm = Path.GetFileName(dll);
        var manifest = PluginManifestGenerator.FromPlugin(plugin, entryAsm, plugin.GetType().FullName!);

        var stage = Path.Combine(Path.GetTempPath(), "ba-pack-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(stage);
        try
        {
            PluginPackageBuilder.WritePluginJson(stage, manifest);
            PluginPackageBuilder.StageLibFromBuildOutput(Path.GetDirectoryName(dll)!, stage, entryAsm);
            PluginPackageBuilder.StageOptionalExtras(Path.GetDirectoryName(project)!, stage);
            PluginPackageBuilder.ValidateStagedPackage(stage, manifest);

            var packageName = $"{plugin.Info.Id}-{plugin.Info.Version}{PluginPackageExtensions.BookPlugin}";
            var packagePath = Path.Combine(outDir, packageName);
            var result = PluginPackageBuilder.CreatePackage(stage, packagePath);

            Console.WriteLine("Packed: " + result.PackagePath);
            Console.WriteLine("SHA-256: " + result.Sha256Hex);
            return 0;
        }
        finally
        {
            try { Directory.Delete(stage, recursive: true); } catch { /* ignore */ }
        }
    }

    private static async Task<int> CmdPrepareRelease(string[] args)
    {
        var project = ResolveProject(GetOpt(args, "--project"));
        var outDir = GetOpt(args, "--out") ?? Path.Combine(Path.GetDirectoryName(project)!, "artifacts");
        if (await CmdPack(["--project", project, "--out", outDir]) != 0)
            return 1;

        var plugin = LoadPluginFromProject(project);
        var package = Directory.GetFiles(outDir, "*" + PluginPackageExtensions.BookPlugin)
            .OrderByDescending(File.GetLastWriteTimeUtc)
            .First();
        var bytes = await File.ReadAllBytesAsync(package);
        var hash = Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(bytes)).ToLowerInvariant();
        var fileName = Path.GetFileName(package);

        var entry = new Dictionary<string, object?>
        {
            ["id"] = plugin.Info.Id,
            ["name"] = plugin.Info.Name,
            ["summary"] = plugin.Info.Description ?? plugin.Info.Name,
            ["description"] = plugin.Info.Description ?? plugin.Info.Name,
            ["publisher"] = new Dictionary<string, object?>
            {
                ["name"] = plugin.Info.Publisher,
                ["githubLogin"] = null,
                ["verified"] = false
            },
            ["pluginType"] = PluginManifestGenerator.ResolveType(plugin).ToString(),
            ["version"] = plugin.Info.Version,
            ["releaseDateUtc"] = null,
            ["minimumAppVersion"] = plugin.Info.MinimumAppVersion,
            ["maximumAppVersion"] = null,
            ["pluginApiVersion"] = PluginApiVersion.Current,
            ["supportedPlatforms"] = new[] { "windows-x64", "any" },
            ["repositoryUrl"] = "https://github.com/OWNER/REPO",
            ["supportUrl"] = plugin.Info.SupportUrl ?? "https://github.com/OWNER/REPO/issues",
            ["documentationUrl"] = plugin.Info.Homepage,
            ["license"] = new Dictionary<string, object?>
            {
                ["spdxId"] = plugin.Info.License,
                ["url"] = null
            },
            ["package"] = new Dictionary<string, object?>
            {
                ["downloadUrl"] = "https://github.com/OWNER/REPO/releases/download/v" + plugin.Info.Version + "/" + fileName,
                ["fileName"] = fileName,
                ["sizeBytes"] = bytes.LongLength,
                ["sha256"] = hash
            },
            ["capabilities"] = PluginManifestGenerator.FromPlugin(plugin, "x.dll", "x").Capabilities,
            ["networkHosts"] = plugin.NetworkHosts.ToArray(),
            ["requiresRestart"] = false,
            ["homepageUrl"] = plugin.Info.Homepage,
            ["changelogUrl"] = null,
            ["deprecated"] = false,
            ["blocked"] = false,
            ["blockedVersions"] = Array.Empty<string>(),
            ["uninstallPluginIds"] = Array.Empty<string>(),
            ["tags"] = Array.Empty<string>()
        };

        await File.WriteAllTextAsync(
            Path.Combine(outDir, "registry-entry.json"),
            JsonSerializer.Serialize(entry, PluginPackageBuilder.JsonOptions));
        await File.WriteAllTextAsync(Path.Combine(outDir, "release-notes.md"),
            $"# {plugin.Info.Name} {plugin.Info.Version}\n\n- \n");
        await File.WriteAllTextAsync(Path.Combine(outDir, "publication-checklist.md"),
            """
            # Publication checklist

            - [ ] Review registry-entry.json download URL
            - [ ] Confirm SHA-256 matches the package
            - [ ] Confirm license and homepage
            - [ ] Open PR against BookAtrium-Community-Plugins
            - [ ] Do not claim BookAtrium support for third-party plugins
            """);

        Console.WriteLine("Release artifacts ready in " + outDir);
        return 0;
    }

    private static BookAtriumPlugin LoadPluginFromProject(string project)
    {
        var dll = PluginPackageBuilder.FindBuiltDll(project, "Release");
        var asm = Assembly.LoadFrom(dll);
        var type = asm.GetTypes().FirstOrDefault(t =>
            t is { IsPublic: true, IsAbstract: false } &&
            typeof(BookAtriumPlugin).IsAssignableFrom(t) &&
            t.GetConstructor(Type.EmptyTypes) is not null)
            ?? throw new InvalidOperationException("No public BookAtriumPlugin subclass with a parameterless constructor was found.");
        return (BookAtriumPlugin)Activator.CreateInstance(type)!;
    }

    private static string ResolveProject(string? explicitPath)
    {
        if (!string.IsNullOrWhiteSpace(explicitPath))
            return Path.GetFullPath(explicitPath);
        var here = Directory.GetFiles(Environment.CurrentDirectory, "*.csproj");
        if (here.Length == 1)
            return here[0];
        throw new InvalidOperationException("Specify --project <path.csproj>");
    }

    private static string? ResolveTemplateName(string type) => type switch
    {
        "store" => "store",
        "metadata-source" => "metadata-source",
        "author-metadata-source" => "author-metadata-source",
        "metadata-reader" => "metadata-reader",
        "metadata-writer" => "metadata-writer",
        "input-converter" or "conversion-input" => "conversion-input",
        "output-converter" or "conversion-output" => "conversion-output",
        "device" => "device",
        _ => null
    };

    private static string? FindTemplatePluginCs(string templateName)
    {
        var embedded = Path.Combine(AppContext.BaseDirectory, "templates", templateName, "Plugin.cs");
        if (File.Exists(embedded))
            return embedded;

        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            var candidate = Path.Combine(dir.FullName, "samples", "templates", "sdk2", templateName, "Plugin.cs");
            if (File.Exists(candidate))
                return candidate;
            dir = dir.Parent;
        }

        return null;
    }

    private static string GenerateCsproj(string assemblyName, string? contractsPath, string projectDir)
    {
        string reference;
        if (!string.IsNullOrWhiteSpace(contractsPath))
        {
            var relative = Path.GetRelativePath(projectDir, Path.GetFullPath(contractsPath)).Replace('\\', '/');
            reference = $"    <ProjectReference Include=\"{relative}\" />";
        }
        else
        {
            reference = $"    <PackageReference Include=\"BookAtrium.PluginContracts\" Version=\"{ContractsPackageVersion}\" />";
        }

        return $"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
                <RootNamespace>{assemblyName}</RootNamespace>
                <AssemblyName>{assemblyName}</AssemblyName>
                <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
              </PropertyGroup>
              <ItemGroup>
            {reference}
              </ItemGroup>
            </Project>
            """ + Environment.NewLine;
    }

    private static string ApplyPlaceholders(string text, string name, string publisher, string id, string className) =>
        text
            .Replace("{{PluginName}}", name)
            .Replace("{{Publisher}}", publisher)
            .Replace("{{PluginId}}", id)
            .Replace("{{ClassName}}", className);

    private static int RunDotNet(params string[] args)
    {
        var psi = new System.Diagnostics.ProcessStartInfo("dotnet")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };
        foreach (var a in args)
            psi.ArgumentList.Add(a);
        using var p = System.Diagnostics.Process.Start(psi)!;
        Console.Write(p.StandardOutput.ReadToEnd());
        Console.Error.Write(p.StandardError.ReadToEnd());
        p.WaitForExit();
        return p.ExitCode;
    }

    private static string? GetOpt(string[] args, string name)
    {
        for (var i = 0; i < args.Length - 1; i++)
        {
            if (string.Equals(args[i], name, StringComparison.OrdinalIgnoreCase))
                return args[i + 1];
        }

        return null;
    }

    private static int Fail(string message)
    {
        Console.Error.WriteLine("error: " + message);
        return 1;
    }

    private static string Slug(string name)
    {
        var sb = new StringBuilder();
        foreach (var ch in name.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(ch))
                sb.Append(ch);
            else if (ch is ' ' or '-' or '_')
                sb.Append('-');
        }

        return sb.ToString().Trim('-');
    }

    private static string SpanPascal(string name)
    {
        var parts = name.Split([' ', '-', '_'], StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p[1..].ToLowerInvariant()));
    }
}
